import type { TemplateDefinition } from '../core/types'

/** All coordinates are in template units. The editor never owns layout coordinates. */
export const birthdayLetter: TemplateDefinition = {
  id: 'birthday-letter',
  version: 1,
  name: '生日来信',
  subtitle: '温暖留白，像一封认真写下的信。',
  tags: ['杂志排版', '照片主角', '随心配色'],
  palettes: [
    { name: '鼠尾草', color: '#75866B' },
    { name: '蔷薇粉', color: '#B97B87' },
    { name: '雾霭蓝', color: '#768FA9' },
    { name: '鸢尾紫', color: '#9786B2' },
    { name: '杏子橙', color: '#CF9B64' },
    { name: '石墨灰', color: '#737571' },
  ],
  layouts: {
    poster: {
      width: 1000,
      height: 1250,
      exportWidth: 2400,
      exportHeight: 3000,
      layers: [
        {
          type: 'text',
          content: { literal: 'A LITTLE LOVE, JUST FOR YOU' },
          x: 62,
          y: 42,
          width: 660,
          height: 30,
          size: 13,
          font: 'sans',
          weight: 500,
          tracking: 3,
          color: 'muted',
        },
        {
          type: 'text',
          content: { literal: 'BIRTHDAY EDITION' },
          x: 720,
          y: 42,
          width: 220,
          height: 30,
          size: 11,
          font: 'sans',
          tracking: 1.7,
          align: 'right',
          color: 'muted',
        },
        {
          type: 'text',
          content: { literal: 'Happy birthday,' },
          x: 57,
          y: 90,
          width: 880,
          height: 140,
          size: 112,
          font: 'serif',
          italic: true,
          color: 'ink',
        },
        {
          type: 'line',
          x: 62,
          y: 242,
          x2: 937,
          y2: 242,
          color: 'accent',
          lineWidth: 1,
          decoration: 'lines',
        },
        { type: 'photo', x: 62, y: 267, width: 876, height: 668 },
        { type: 'rect', x: 785, y: 289, width: 130, height: 144, color: 'paper', opacity: 0.96 },
        {
          type: 'text',
          content: { literal: 'YOUR DAY' },
          x: 792,
          y: 309,
          width: 116,
          height: 25,
          size: 12,
          tracking: 1.5,
          font: 'sans',
          align: 'center',
          color: 'muted',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 790,
          y: 341,
          width: 120,
          height: 58,
          size: 41,
          font: 'serif',
          weight: 600,
          align: 'center',
          color: 'ink',
        },
        {
          type: 'line',
          x: 824,
          y: 413,
          x2: 876,
          y2: 413,
          color: 'accent',
          lineWidth: 1,
          decoration: 'lines',
        },
        {
          type: 'text',
          content: 'name',
          x: 62,
          y: 962,
          width: 800,
          height: 82,
          size: 47,
          minSize: 26,
          maxLines: 2,
          lineHeight: 1.25,
          font: 'sans',
          weight: 500,
          color: 'ink',
        },
        { type: 'sparkle', x: 907, y: 996, size: 31, color: 'accent', decoration: 'sparkles' },
        {
          type: 'text',
          content: 'wish',
          x: 64,
          y: 1052,
          width: 874,
          height: 136,
          size: 24,
          minSize: 18,
          lineHeight: 1.5,
          maxLines: 5,
          font: 'sans',
          color: 'ink',
        },
        {
          type: 'line',
          x: 62,
          y: 1200,
          x2: 937,
          y2: 1200,
          color: 'accent',
          decoration: 'lines',
          lineWidth: 0.7,
        },
        {
          type: 'text',
          content: { literal: 'ALL MY LOVE, ALWAYS.' },
          x: 64,
          y: 1208,
          width: 450,
          height: 24,
          size: 10,
          tracking: 2.2,
          font: 'sans',
          color: 'muted',
        },
        {
          type: 'text',
          content: { literal: '♡' },
          x: 890,
          y: 1205,
          width: 47,
          height: 27,
          size: 19,
          align: 'right',
          font: 'sans',
          color: 'accent',
          decoration: 'sparkles',
        },
      ],
    },
    avatar: {
      width: 1000,
      height: 1000,
      exportWidth: 1600,
      exportHeight: 1600,
      layers: [
        { type: 'rect', x: 0, y: 0, width: 1000, height: 1000, color: 'soft' },
        { type: 'photo', x: 45, y: 45, width: 910, height: 910 },
        {
          type: 'rect',
          x: 28,
          y: 28,
          width: 944,
          height: 944,
          color: 'accent',
          stroke: true,
          lineWidth: 1.4,
          decoration: 'lines',
        },
        { type: 'rect', x: 222, y: 102, width: 556, height: 58, color: 'paper', opacity: 0.96 },
        {
          type: 'text',
          content: { literal: 'HAPPY BIRTHDAY' },
          x: 238,
          y: 115,
          width: 524,
          height: 34,
          size: 24,
          tracking: 4.5,
          font: 'serif',
          weight: 600,
          align: 'center',
          color: 'ink',
        },
        { type: 'rect', x: 164, y: 728, width: 672, height: 162, color: 'paper', opacity: 0.97 },
        {
          type: 'text',
          content: 'name',
          x: 194,
          y: 744,
          width: 612,
          height: 82,
          size: 47,
          minSize: 25,
          maxLines: 2,
          lineHeight: 1.25,
          font: 'sans',
          weight: 500,
          align: 'center',
          vertical: 'center',
          color: 'ink',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 300,
          y: 835,
          width: 400,
          height: 39,
          size: 30,
          font: 'serif',
          weight: 600,
          align: 'center',
          color: 'ink',
          tracking: 2,
        },
        { type: 'sparkle', x: 750, y: 844, size: 17, color: 'accent', decoration: 'sparkles' },
        { type: 'sparkle', x: 250, y: 844, size: 17, color: 'accent', decoration: 'sparkles' },
      ],
    },
  },
}
