import type { TemplateDefinition } from '../core/types'

export const centerStage: TemplateDefinition = {
  id: 'center-stage',
  version: 1,
  name: '此刻主场',
  colorMode: 'dark',
  subtitle: '灯光亮起，今天的主角是你。',
  tags: ['深色舞台', '醒目字排', '应援色块'],
  palettes: [
    { name: '荧光柠', color: '#D5ED79' },
    { name: '电光紫', color: '#B79AE8' },
    { name: '玫瑰信号', color: '#ED879F' },
    { name: '冰川蓝', color: '#82CDE1' },
    { name: '橙色现场', color: '#F0AC76' },
    { name: '银白', color: '#D6D9DF' },
  ],
  layouts: {
    avatar: {
      width: 1000,
      height: 1000,
      exportWidth: 1600,
      exportHeight: 1600,
      layers: [
        { type: 'rect', x: 270, y: 42, width: 686, height: 773, color: 'soft' },
        { type: 'photo', x: 292, y: 65, width: 642, height: 738 },
        { type: 'rect', x: 247, y: 65, width: 13, height: 489, color: 'accent' },
        {
          type: 'text',
          content: { id: 'avatar-heading-top', literal: 'YOUR' },
          x: 93,
          y: 237,
          width: 170,
          height: 46,
          size: 30,
          weight: 600,
          font: 'sans',
          tracking: 2,
          color: 'ink',
        },
        {
          type: 'text',
          content: { id: 'avatar-heading-bottom', literal: 'DAY.' },
          x: 92,
          y: 284,
          width: 177,
          height: 59,
          size: 46,
          weight: 600,
          font: 'sans',
          color: 'ink',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 90,
          y: 357,
          width: 179,
          height: 56,
          size: 42,
          font: 'serif',
          weight: 600,
          color: 'ink',
        },
        {
          type: 'line',
          x: 97,
          y: 443,
          x2: 215,
          y2: 443,
          color: 'muted',
          lineWidth: 2,
          decoration: 'lines',
        },
        { type: 'sparkle', x: 157, y: 508, size: 28, color: 'accent', decoration: 'sparkles' },
        { type: 'rect', x: 146, y: 690, width: 710, height: 169, color: 'accent' },
        {
          type: 'text',
          content: 'name',
          x: 171,
          y: 714,
          width: 660,
          height: 121,
          size: 63,
          minSize: 24,
          maxLines: 3,
          lineHeight: 1.2,
          font: 'sans',
          weight: 600,
          color: 'onAccent',
          align: 'center',
          vertical: 'center',
        },
        {
          type: 'text',
          content: { id: 'avatar-footer', literal: 'BORN TO SHINE' },
          x: 245,
          y: 888,
          width: 510,
          height: 37,
          size: 18,
          tracking: 4,
          font: 'sans',
          color: 'muted',
          align: 'center',
        },
      ],
    },
    poster: {
      width: 1000,
      height: 1250,
      exportWidth: 2400,
      exportHeight: 3000,
      layers: [
        { type: 'rect', x: 351, y: 44, width: 605, height: 912, color: 'soft' },
        { type: 'photo', x: 371, y: 66, width: 563, height: 868 },
        {
          type: 'text',
          content: { id: 'poster-kicker', literal: 'THE SPOTLIGHT IS YOURS' },
          x: 61,
          y: 42,
          width: 700,
          height: 32,
          size: 11,
          tracking: 2.5,
          font: 'sans',
          color: 'ink',
        },
        {
          type: 'text',
          content: { id: 'poster-heading', literal: 'TODAY,' },
          x: 60,
          y: 109,
          width: 285,
          height: 45,
          size: 22,
          tracking: 3,
          font: 'sans',
          weight: 500,
          color: 'muted',
        },
        {
          type: 'text',
          content: 'name',
          x: 54,
          y: 185,
          width: 295,
          height: 295,
          size: 88,
          minSize: 24,
          maxLines: 6,
          lineHeight: 1.12,
          font: 'sans',
          weight: 600,
          color: 'ink',
        },
        { type: 'rect', x: 58, y: 523, width: 259, height: 146, color: 'accent' },
        {
          type: 'text',
          content: { id: 'poster-photo-label', literal: 'BIRTHDAY / LIVE' },
          x: 75,
          y: 543,
          width: 222,
          height: 28,
          size: 10,
          font: 'sans',
          tracking: 1.7,
          color: 'onAccent',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 72,
          y: 583,
          width: 229,
          height: 65,
          size: 59,
          font: 'sans',
          weight: 600,
          color: 'onAccent',
        },
        {
          type: 'text',
          content: { id: 'poster-message', literal: 'ALL EYES\nON YOU.' },
          x: 58,
          y: 730,
          width: 280,
          height: 116,
          size: 35,
          font: 'sans',
          weight: 600,
          lineHeight: 1.25,
          maxLines: 2,
          color: 'ink',
        },
        {
          type: 'line',
          x: 62,
          y: 907,
          x2: 245,
          y2: 907,
          lineWidth: 1,
          color: 'muted',
          decoration: 'lines',
        },
        { type: 'sparkle', x: 303, y: 904, size: 22, color: 'accent', decoration: 'sparkles' },
        { type: 'rect', x: 60, y: 983, width: 875, height: 5, color: 'accent' },
        {
          type: 'text',
          content: 'wish',
          x: 62,
          y: 1023,
          width: 875,
          height: 152,
          size: 25,
          minSize: 18,
          lineHeight: 1.4,
          maxLines: 6,
          font: 'sans',
          color: 'ink',
        },
        {
          type: 'text',
          content: { id: 'poster-footer', literal: 'HAPPY BIRTHDAY. KEEP SHINING.' },
          x: 62,
          y: 1201,
          width: 800,
          height: 27,
          size: 11,
          tracking: 2.2,
          font: 'sans',
          color: 'muted',
        },
      ],
    },
  },
}
