import type { TemplateDefinition } from '../core/types'

export const heartPolaroid: TemplateDefinition = {
  id: 'heart-polaroid',
  version: 1,
  name: '心动拍立得',
  subtitle: '把这一刻，收进一张小小相纸。',
  tags: ['相纸层次', '日常心动', '留住瞬间'],
  palettes: [
    { name: '莓果奶昔', color: '#B97B87' },
    { name: '开心果', color: '#8A9874' },
    { name: '奶油杏', color: '#C69C71' },
    { name: '晴日蓝', color: '#7D9BAE' },
    { name: '薰衣草', color: '#A18BB8' },
    { name: '可可', color: '#9A8274' },
  ],
  layouts: {
    avatar: {
      width: 1000,
      height: 1000,
      exportWidth: 1600,
      exportHeight: 1600,
      layers: [
        { type: 'rect', x: 0, y: 0, width: 1000, height: 1000, color: 'soft' },
        { type: 'rect', x: 104, y: 83, width: 818, height: 850, color: 'accent', opacity: 0.22 },
        { type: 'rect', x: 70, y: 52, width: 824, height: 856, color: 'paper' },
        { type: 'rect', x: 88, y: 67, width: 824, height: 856, color: 'white' },
        { type: 'photo', x: 116, y: 96, width: 768, height: 604 },
        { type: 'rect', x: 690, y: 67, width: 164, height: 44, color: 'soft', decoration: 'lines' },
        {
          type: 'text',
          content: { id: 'avatar-caption', literal: 'a moment to keep' },
          x: 152,
          y: 721,
          width: 696,
          height: 40,
          size: 27,
          font: 'serif',
          italic: true,
          color: 'muted',
          align: 'center',
        },
        {
          type: 'text',
          content: 'name',
          x: 156,
          y: 769,
          width: 688,
          height: 82,
          size: 43,
          minSize: 24,
          lineHeight: 1.25,
          maxLines: 2,
          font: 'sans',
          weight: 500,
          color: 'ink',
          align: 'center',
          vertical: 'center',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 330,
          y: 861,
          width: 340,
          height: 38,
          size: 28,
          tracking: 3,
          font: 'serif',
          weight: 600,
          align: 'center',
          color: 'muted',
        },
        { type: 'sparkle', x: 113, y: 727, size: 19, color: 'accent', decoration: 'sparkles' },
        { type: 'sparkle', x: 936, y: 310, size: 28, color: 'accent', decoration: 'sparkles' },
        {
          type: 'line',
          x: 410,
          y: 949,
          x2: 590,
          y2: 949,
          color: 'accent',
          lineWidth: 2,
          decoration: 'lines',
        },
      ],
    },
    poster: {
      width: 1000,
      height: 1250,
      exportWidth: 2400,
      exportHeight: 3000,
      layers: [
        { type: 'rect', x: 0, y: 0, width: 1000, height: 1250, color: 'soft' },
        {
          type: 'text',
          content: { id: 'poster-kicker', literal: 'MOMENTS OF YOU' },
          x: 65,
          y: 39,
          width: 550,
          height: 32,
          size: 13,
          font: 'sans',
          tracking: 3,
          color: 'muted',
        },
        {
          type: 'text',
          content: { id: 'poster-edition', literal: '01 / BIRTHDAY' },
          x: 685,
          y: 39,
          width: 250,
          height: 32,
          size: 12,
          font: 'sans',
          tracking: 1.6,
          align: 'right',
          color: 'muted',
        },
        { type: 'rect', x: 103, y: 117, width: 794, height: 870, color: 'accent', opacity: 0.23 },
        { type: 'rect', x: 69, y: 105, width: 806, height: 861, color: 'paper' },
        { type: 'rect', x: 86, y: 85, width: 796, height: 874, color: 'white' },
        { type: 'photo', x: 116, y: 118, width: 736, height: 655 },
        { type: 'rect', x: 701, y: 95, width: 201, height: 125, color: 'paper' },
        {
          type: 'text',
          content: { id: 'poster-photo-label', literal: 'THE DAY I KEEP' },
          x: 716,
          y: 113,
          width: 171,
          height: 24,
          size: 10,
          font: 'sans',
          tracking: 1.4,
          align: 'center',
          color: 'muted',
        },
        {
          type: 'text',
          content: 'birthday',
          x: 716,
          y: 148,
          width: 171,
          height: 58,
          size: 44,
          font: 'serif',
          weight: 600,
          align: 'center',
          color: 'ink',
        },
        {
          type: 'text',
          content: { id: 'poster-heading', literal: 'Happy you day.' },
          x: 120,
          y: 796,
          width: 685,
          height: 49,
          size: 37,
          font: 'serif',
          italic: true,
          color: 'muted',
        },
        {
          type: 'text',
          content: 'name',
          x: 121,
          y: 859,
          width: 709,
          height: 76,
          size: 42,
          minSize: 24,
          lineHeight: 1.25,
          maxLines: 2,
          font: 'sans',
          weight: 500,
          color: 'ink',
        },
        {
          type: 'text',
          content: 'wish',
          x: 76,
          y: 1010,
          width: 848,
          height: 164,
          size: 26,
          minSize: 18,
          maxLines: 6,
          lineHeight: 1.45,
          font: 'sans',
          color: 'ink',
        },
        {
          type: 'line',
          x: 76,
          y: 1192,
          x2: 924,
          y2: 1192,
          color: 'accent',
          lineWidth: 1,
          decoration: 'lines',
        },
        {
          type: 'text',
          content: { id: 'poster-footer', literal: 'A SMALL FRAME. A WHOLE LOT OF LOVE.' },
          x: 76,
          y: 1205,
          width: 755,
          height: 24,
          size: 10,
          tracking: 2,
          font: 'sans',
          color: 'muted',
        },
        { type: 'sparkle', x: 924, y: 820, size: 27, color: 'accent', decoration: 'sparkles' },
        { type: 'sparkle', x: 57, y: 547, size: 15, color: 'accent', decoration: 'sparkles' },
      ],
    },
  },
}
