import type { CardTemplateDefinition, Layer } from '../core/types'

const palettes = [
  { name: '鼠尾草', color: '#75866B' },
  { name: '玫瑰灰', color: '#AD7F8A' },
  { name: '雾蓝', color: '#7898AA' },
  { name: '暖杏', color: '#BA936E' },
]
const text = (
  content: 'name' | 'wish' | 'date',
  x: number,
  y: number,
  width: number,
  height: number,
  size: number,
  minSize: number,
  maxLines: number,
): Layer => ({
  type: 'text',
  content,
  x,
  y,
  width,
  height,
  size,
  minSize,
  maxLines,
  lineHeight: 1.3,
  font: 'sans',
  color: content === 'name' ? 'ink' : 'muted',
  weight: content === 'name' ? 500 : 400,
})

export const cardTemplates: CardTemplateDefinition[] = [
  {
    id: 'photo-strip',
    version: 1,
    name: '上下照片条',
    subtitle: '两帧并置，把日常收成一封短笺。',
    palettes,
    layout: {
      width: 900,
      height: 1200,
      exportWidth: 1800,
      exportHeight: 2400,
      layers: [
        { type: 'rect', x: 30, y: 30, width: 840, height: 1140, color: 'soft' },
        { type: 'rect', x: 46, y: 46, width: 808, height: 1108, color: 'paper' },
        {
          type: 'text',
          content: { id: 'card-heading', literal: 'TWO FRAMES, ONE STORY' },
          x: 84,
          y: 77,
          width: 700,
          height: 30,
          size: 19,
          tracking: 3,
          font: 'serif',
          color: 'muted',
        },
        { type: 'photo', slot: 'first', x: 84, y: 132, width: 732, height: 330 },
        { type: 'photo', slot: 'second', x: 84, y: 480, width: 732, height: 330 },
        {
          type: 'line',
          x: 84,
          y: 851,
          x2: 816,
          y2: 851,
          color: 'accent',
          lineWidth: 2,
          decoration: 'lines',
        },
        text('name', 84, 880, 680, 94, 42, 22, 2),
        text('wish', 84, 981, 732, 86, 24, 18, 3),
        text('date', 84, 1100, 500, 28, 18, 18, 1),
        { type: 'sparkle', x: 793, y: 1120, size: 17, color: 'accent', decoration: 'sparkles' },
      ],
    },
  },
  {
    id: 'portrait-collage',
    version: 1,
    name: '写真拼贴',
    subtitle: '一张主写真，一张随身珍藏的小相纸。',
    palettes,
    layout: {
      width: 900,
      height: 1200,
      exportWidth: 1800,
      exportHeight: 2400,
      layers: [
        { type: 'rect', x: 0, y: 0, width: 900, height: 1200, color: 'soft' },
        { type: 'rect', x: 34, y: 34, width: 832, height: 1132, color: 'paper' },
        { type: 'photo', slot: 'first', x: 66, y: 68, width: 612, height: 686 },
        { type: 'rect', x: 499, y: 461, width: 352, height: 390, color: 'accent', opacity: 0.23 },
        { type: 'rect', x: 478, y: 440, width: 352, height: 390, color: 'white' },
        { type: 'photo', slot: 'second', x: 494, y: 456, width: 320, height: 304 },
        {
          type: 'text',
          content: { id: 'card-caption', literal: 'a moment to keep' },
          x: 505,
          y: 784,
          width: 294,
          height: 36,
          size: 27,
          font: 'serif',
          italic: true,
          align: 'center',
          color: 'muted',
        },
        {
          type: 'rect',
          x: 568,
          y: 426,
          width: 169,
          height: 30,
          color: 'soft',
          decoration: 'lines',
        },
        {
          type: 'text',
          content: { id: 'card-heading', literal: 'LITTLE MOMENTS /' },
          x: 70,
          y: 805,
          width: 400,
          height: 28,
          size: 18,
          tracking: 2,
          font: 'serif',
          color: 'muted',
        },
        text('name', 70, 866, 735, 101, 46, 22, 2),
        text('wish', 70, 983, 735, 86, 24, 18, 3),
        { type: 'line', x: 70, y: 1093, x2: 830, y2: 1093, color: 'accent', decoration: 'lines' },
        text('date', 70, 1112, 580, 28, 18, 18, 1),
        { type: 'sparkle', x: 765, y: 184, size: 32, color: 'accent', decoration: 'sparkles' },
        { type: 'sparkle', x: 796, y: 230, size: 12, color: 'accent', decoration: 'sparkles' },
      ],
    },
  },
]

export function getCardTemplate(id: string) {
  const template = cardTemplates.find((item) => item.id === id)
  if (!template) throw new Error('这份电子小卡使用的布局尚未安装。原作品仍保留。')
  return template
}
